server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/ai‑chain‑lab?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrlInLocalInfile=true
    username: root
    password: qwer4321

    hikari:
      connection-test-query: SElECT 1  # 自动检测连接
      connection-timeout: 60000  # 数据库获取连接超时时间，默认30s
      idle-timeout: 5000000  # 空闲连接存活最大时间，默认30min
      max-lifetime: 5400000  # 池中连接最大空闲时间，默认30min
      maximum-pool-size: 12  # 连接池最大连接数 ，默认10
      minimum-idle: 12  #最小空闲连接数
      pool-name: SPHHikariPool   # 连接池名称

# 打印生成的DDL，便于测试
mybatis-plus:
  config-location:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl