server:
  port: 8092

logging:
  config: classpath:logback-config.xml
  level:
    root: info
    cn.gpt: debug

spring:
  application:
    name: Web-Chat

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: true  # 启用服务发现
        # username: ${spring.cloud.nacos.username}
        # password: ${spring.cloud.nacos.password}
      config:
        import-check:
          enabled: false  # 禁用配置导入检查

