server:
  port: 1000

logging:
  config: classpath:logback-config.xml  # 使用自定义 logback 配置
  level:
    root: info
    org.springframework.cloud.gateway: debug  # Gateway 详细日志
    com.alibaba.nacos: info

spring:
  application:
    name: Server-Gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: true  # 启用服务发现
      #        username: ${spring.cloud.nacos.username}
      #        password: ${spring.cloud.nacos.password}
      # nacos-server:8848
      config:
        import-check:
          enabled: false  # 禁用配置导入检查
    
    gateway:
      discovery:
        locator:
          enabled: true  # 启用服务发现路由
          lower-case-service-id: true  # 服务名小写
      routes:
        - id: auth-service
          uri: lb://Web-Auth  # 负载均衡到 Web-Auth 服务
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        
        - id: chat-service
          uri: lb://Web-Chat
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1
        
        - id: file-service
          uri: lb://Web-File
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
